### PR TITLE
experimenting

### PR DESCRIPTION
**Pull request by borod108**
[WIP] adding probing api

### CODE REVIEW

**Comment by akostadinov** [comment]
I couldn't find the exact repo in gerrit where this code is present. Can somebody paste exact master repo link in project description?

**Comment by machacekondra** [comment]
@akostadinov It's here: https://gerrit.ovirt.org/#/admin/projects/ovirt-engine-sdk-ruby

**Comment by akostadinov** [comment]
Thank you, would be useful to put this link in project description if you can.

**Comment by mykaul** [comment]
@akostadinov - done.

**Pull request closed without merging**
